// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;


function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * createClient throws outright when the URL is missing, and this module is
 * imported at the app root by AuthProvider. One unset environment variable
 * therefore takes the ENTIRE site down with a blank page — including every
 * page that never touches auth — and the build that produced it succeeds with
 * no warning, so the first sign of trouble is a white screen in production.
 *
 * Fall back to a syntactically valid placeholder so the module loads, and
 * expose a flag the auth layer can check. Auth degrades; the library renders.
 */
export const supabaseConfigured = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

if (!supabaseConfigured && typeof console !== "undefined") {
  console.warn(
    "[supabase] VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY are not set. " +
      "Sign-in and subscribe are disabled; the rest of the site is unaffected."
  );
}

const RESOLVED_URL = SUPABASE_URL || "https://unconfigured.invalid";
const RESOLVED_KEY = SUPABASE_PUBLISHABLE_KEY || "unconfigured";

export const supabase = createClient<Database>(RESOLVED_URL, RESOLVED_KEY, {
  global: {
    fetch: createSupabaseFetch(RESOLVED_KEY),
  },
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});
